package de.hpi.semrecsys;

import java.beans.Transient;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated Jun 23, 2014 2:32:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class CategoryTable implements DBObject {

	private int categoryId;
	private int parentId;
	private int childrenCount;
	private int level;
	private String value;
	private String path;

	public CategoryTable() {
	}

	public CategoryTable(int categoryId, int parentId, int childrenCount, int level, String path) {
		this.categoryId = categoryId;
		this.parentId = parentId;
		this.childrenCount = childrenCount;
		this.level = level;
		this.path = path;
	}

	public CategoryTable(int categoryId, int parentId, int childrenCount, int level, String value, String path) {
		this.categoryId = categoryId;
		this.parentId = parentId;
		this.childrenCount = childrenCount;
		this.level = level;
		this.value = value;
		this.path = path;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "children_count", nullable = false)
	public int getChildrenCount() {
		return this.childrenCount;
	}

	public void setChildrenCount(int childrenCount) {
		this.childrenCount = childrenCount;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "path", nullable = false)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Override
	@Transient
	public Serializable getId() {
		return getCategoryId();
	}

	public void setId(int id) {
	}

}
