package de.hpi.semrecsys;

// default package
// Generated Aug 12, 2014 6:25:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Recommendation of type "generated"
 * recommendation generated by hbm2java
 */
@Entity
@Table(name = "recommendation")
public class GeneratedRecommendation extends RecommendationImpl {

	public static String type = "generated";

	public GeneratedRecommendation() {
	}

	public GeneratedRecommendation(RecommendationId id, String linkedProductId) {
		super(id, linkedProductId);
		id.setType(type);
	}

	public String recommendationType() {
		return type;
	}

}
