package de.hpi.semrecsys;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * recommendation of type "random" used for random recommendations
 * recommendation generated by hbm2java
 */
@Entity
@Table(name = "recommendation")
public class RandomRecommendation extends RecommendationImpl {
	public static String type = "random";

	public RandomRecommendation() {
	}

	public RandomRecommendation(RecommendationId id, String linkedProductId) {
		super(id, linkedProductId);
		id.setType(type);
	}

	@Override
	public String recommendationType() {
		return type;
	}

}
