package de.hpi.semrecsys;

// default package
// Generated Aug 12, 2014 6:25:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SimilarProductId generated by hbm2java
 */
@Embeddable
public class RecommendationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String productId;
	private String type;
	private int position;

	public RecommendationId() {
	}

	public RecommendationId(String productId, int position) {
		this.productId = productId;
		this.position = position;
	}

	@Column(name = "product_id", nullable = false)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecommendationId))
			return false;
		RecommendationId castOther = (RecommendationId) other;

		return (this.getProductId() == castOther.getProductId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this
						.getType().equals(castOther.getType()))) && (this.getPosition() == castOther.getPosition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId().hashCode();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + this.getPosition();

		return result;
	}

}
