package de.hpi.semrecsys;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated Aug 12, 2014 6:25:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * recommendation of type "cross_sell" used for existing recommendations
 * recommendation generated by hbm2java
 */
@Entity
@Table(name = "recommendation")
public class SystemRecommendation extends RecommendationImpl {
	public static String type = "cross_sell";

	public SystemRecommendation() {

	}

	public SystemRecommendation(RecommendationId id, Integer linkedProductId) {
		super(id, linkedProductId);
		id.setType(type);
	}

	@Override
	public String recommendationType() {
		return type;
	}
}
